version: '3'

services: 
    db:
        image: mysql/mysql-server
        container_name: 'mysqldb'
        command: mysqld --character-set-server=utf8 --collation_server=utf8_general_ci
        restart: always
        ports: 
            - '3306:3306'
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: lisa
            MYSQL_PASSWORD: lisa
        volumes: 
            - /root/docker/mysql/mysql-init:/docker-entrypoint-initdb.d
            - /root/docker/mysql/data:/var/lib/mysql       
    web:
        build: .
        container_name: 'webapi'
        restart: always
        ports:
            - '8003:80'
        depends_on: 
            - db
