version: '3'

services: 
    mongodb:
        image: mongo
        container_name: 'mongodb'
        restart: always
        ports: 
            - '27017:27017'
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes: 
            - /root/docker/mongo/config:/data/configdb/
            - /root/docker/mongo/db:/data/db

#  docker run -d -p 27017:27017\
#  --restart always\
#  --name mongodb\
#  -e MONGO_INITDB_ROOT_USERNAME=root\
#  -e MONGO_INITDB_ROOT_PASSWORD=root\
#  -v /root/docker/mongo/config:/data/configdb\
#  -v /root/docker/mongo/db:/data/db mongo --auth
#  db.createUser({ user: 'root', pwd: 'root', roles: [ { role: "userAdminAnyDatabase", db: "admin" } ] }); 

# docker run -d  --restart always\
#  --hostname localhost --name rabbit\
#  -e RABBITMQ_DEFAULT_USER=admin\
#  -e RABBITMQ_DEFAULT_PASS=lisa\
#  -p 15672:15672 -p 5672:5672 -p 25672:25672 -p 61613:61613 -p 1883:1883\
#  -v /root/docker/rabbitmq:/var/lib/rabbitmq\
#   rabbitmq:3-management

# rabbitmqctl add_user admin lisa
# rabbitmqctl set_user_tags admin administrator
# rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"



